title: SpaceSheep
email: spacesheep@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A description
baseurl: ""
url: "https://spacesheep.dev"
twitter_username: sheepsixteen
github_username: sheepsixteen


# No theme
theme: 

# All plugins are enabled by the github-pages gem
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
